- name: be sure telegraf is installed with a specific version
  yum: name=telegraf-1.3.5-1 state=present
  tags: telegraf

- name: be sure telegraf is configured
  template: src=telegraf.conf.j2 dest=/etc/telegraf/telegraf.conf
  tags: telegraf

- name: be sure telegraf is running and enabled
  service: name=telegraf state=started enabled=yes
  tags: telegraf
